import React, { useState, useEffect, useMemo } from 'react';
import Card from './common/Card';
import Button from './common/Button';
import {
  DownloadIcon,
  SearchIcon,
  FilterIcon,
  RefreshCwIcon,
  FileTextIcon,
  CopyIcon,
  CheckIcon,
  DatabaseIcon,
  AlertTriangleIcon,
  TagIcon,
  UsersIcon,
  CheckCircleIcon
} from './common/icons';
import type { RegionalAlert, UserActivityLog, GhanaRegion } from '../types';
import {
  fetchRegionalAlerts,
  fetchUserActivityLogs,
  exportRegionalAlertsToCSV,
  exportUserActivityLogsToCSV
} from '../services/activityLogger';

const GHANA_REGIONS: GhanaRegion[] = [
  'All Regions',
  'Greater Accra',
  'Ashanti',
  'Bono / Techiman',
  'Northern / Tamale',
  'Eastern',
  'Western',
  'Central',
  'Volta',
  'Upper East',
  'Upper West',
  'Southern Coastal',
  'Middle Forest',
  'Northern Savannah'
];

const BACKEND_SQL_QUERY = `-- ====================================================================
-- SUPABASE MIGRATION: USER ACTIVITY LOGS & AUDIT CSV EXPORT
-- Ghana Farmers Market℠ Admin Console
-- ====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. USER ACTIVITY LOGS TABLE
CREATE TABLE IF NOT EXISTS public.user_activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    user_name TEXT,
    user_email TEXT,
    user_type TEXT DEFAULT 'farmer' CHECK (user_type IN ('farmer', 'buyer', 'seller', 'admin', 'system')),
    action TEXT NOT NULL,
    details TEXT NOT NULL,
    region TEXT NOT NULL DEFAULT 'All Regions',
    ip_address TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optimize index for speedy CSV export and admin filtering
CREATE INDEX IF NOT EXISTS idx_user_activity_logs_created_at ON public.user_activity_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_activity_logs_action ON public.user_activity_logs (action);
CREATE INDEX IF NOT EXISTS idx_user_activity_logs_region ON public.user_activity_logs (region);
CREATE INDEX IF NOT EXISTS idx_user_activity_logs_user_id ON public.user_activity_logs (user_id);

-- 3. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.user_activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert to user_activity_logs"
ON public.user_activity_logs FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "Allow read access to user_activity_logs"
ON public.user_activity_logs FOR SELECT
TO anon, authenticated
USING (true);

-- 4. STORED PROCEDURE: LOG ACTIVITY
CREATE OR REPLACE FUNCTION public.log_user_activity(
    p_user_id TEXT,
    p_user_name TEXT,
    p_user_email TEXT,
    p_user_type TEXT,
    p_action TEXT,
    p_details TEXT,
    p_region TEXT DEFAULT 'All Regions',
    p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_log_id BIGINT;
BEGIN
    INSERT INTO public.user_activity_logs (
        user_id, user_name, user_email, user_type, action, details, region, metadata, created_at
    )
    VALUES (
        p_user_id, p_user_name, p_user_email, COALESCE(p_user_type, 'farmer'),
        p_action, p_details, COALESCE(p_region, 'All Regions'),
        COALESCE(p_metadata, '{}'::jsonb), timezone('utc'::text, now())
    )
    RETURNING id INTO new_log_id;
    RETURN new_log_id;
END;
$$;

-- 5. FLATTENED VIEWS FOR EASY CSV EXPORT
CREATE OR REPLACE VIEW public.v_export_regional_alerts AS
SELECT 
    id AS "Alert ID",
    type AS "Alert Type",
    region AS "Region",
    severity AS "Severity Level",
    title AS "Title",
    message AS "Message Content",
    COALESCE(metadata::text, '') AS "Metadata JSON",
    to_char(created_at, 'YYYY-MM-DD HH24:MI:SS') AS "Created At (UTC)",
    COALESCE(created_by::text, 'System Automated') AS "Created By"
FROM public.regional_alerts
ORDER BY created_at DESC;

CREATE OR REPLACE VIEW public.v_export_user_activity_logs AS
SELECT 
    id AS "Log ID",
    to_char(created_at, 'YYYY-MM-DD HH24:MI:SS') AS "Timestamp (UTC)",
    COALESCE(user_id, 'Guest') AS "User ID",
    COALESCE(user_name, 'Anonymous') AS "User Name",
    COALESCE(user_email, 'N/A') AS "Email Address",
    COALESCE(user_type, 'farmer') AS "User Role",
    action AS "Action Taken",
    region AS "Region",
    details AS "Event Details",
    COALESCE(metadata::text, '') AS "Metadata JSON"
FROM public.user_activity_logs
ORDER BY created_at DESC;

-- 6. AUDIT SUMMARY METRICS FUNCTION
CREATE OR REPLACE FUNCTION public.get_audit_summary()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    total_alerts BIGINT;
    total_logs BIGINT;
    weather_alerts BIGINT;
    price_alerts BIGINT;
    unique_users BIGINT;
BEGIN
    SELECT count(*) INTO total_alerts FROM public.regional_alerts;
    SELECT count(*) INTO total_logs FROM public.user_activity_logs;
    SELECT count(*) INTO weather_alerts FROM public.regional_alerts WHERE type = 'weather';
    SELECT count(*) INTO price_alerts FROM public.regional_alerts WHERE type = 'price';
    SELECT count(DISTINCT user_id) INTO unique_users FROM public.user_activity_logs WHERE user_id IS NOT NULL;

    RETURN jsonb_build_object(
        'total_regional_alerts', total_alerts,
        'total_user_activity_logs', total_logs,
        'weather_alerts_count', weather_alerts,
        'price_alerts_count', price_alerts,
        'unique_active_users', unique_users,
        'generated_at', timezone('utc'::text, now())
    );
END;
$$;

-- 7. USER FILES SCHEMA & CACHE SYNC (Fixes 'download_url' column schema cache error)
CREATE TABLE IF NOT EXISTS public.user_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    download_url TEXT,
    storage_path TEXT,
    file_name TEXT,
    file_type TEXT,
    context TEXT,
    ai_summary TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.user_files ADD COLUMN IF NOT EXISTS download_url TEXT;
ALTER TABLE public.user_files ADD COLUMN IF NOT EXISTS storage_path TEXT;
ALTER TABLE public.user_files ADD COLUMN IF NOT EXISTS file_name TEXT;
ALTER TABLE public.user_files ADD COLUMN IF NOT EXISTS file_type TEXT;
ALTER TABLE public.user_files ADD COLUMN IF NOT EXISTS context TEXT;
ALTER TABLE public.user_files ADD COLUMN IF NOT EXISTS ai_summary TEXT;
ALTER TABLE public.user_files ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.user_files ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

NOTIFY pgrst, 'reload schema';`;

const AdminAuditExport: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'alerts' | 'activity' | 'sql'>('alerts');
  const [alerts, setAlerts] = useState<RegionalAlert[]>([]);
  const [activityLogs, setActivityLogs] = useState<UserActivityLog[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedRegion, setSelectedRegion] = useState<string>('All Regions');
  const [selectedSeverity, setSelectedSeverity] = useState<string>('all');
  const [copiedSql, setCopiedSql] = useState(false);
  const [exportNotice, setExportNotice] = useState<string | null>(null);

  // Load live alerts & activity logs
  const loadData = async () => {
    setIsLoading(true);
    try {
      const [fetchedAlerts, fetchedLogs] = await Promise.all([
        fetchRegionalAlerts(),
        fetchUserActivityLogs()
      ]);
      setAlerts(fetchedAlerts);
      setActivityLogs(fetchedLogs);
    } catch (err) {
      console.error("Error loading audit data:", err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  // Filtered Regional Alerts
  const filteredAlerts = useMemo(() => {
    return alerts.filter(alert => {
      const matchesRegion =
        selectedRegion === 'All Regions' ||
        alert.region.toLowerCase().includes(selectedRegion.toLowerCase()) ||
        alert.region === 'All Regions';

      const matchesSeverity =
        selectedSeverity === 'all' || alert.severity === selectedSeverity;

      const q = searchQuery.toLowerCase().trim();
      const matchesSearch =
        !q ||
        alert.title.toLowerCase().includes(q) ||
        alert.message.toLowerCase().includes(q) ||
        alert.region.toLowerCase().includes(q) ||
        alert.type.toLowerCase().includes(q);

      return matchesRegion && matchesSeverity && matchesSearch;
    });
  }, [alerts, selectedRegion, selectedSeverity, searchQuery]);

  // Filtered Activity Logs
  const filteredLogs = useMemo(() => {
    return activityLogs.filter(log => {
      const matchesRegion =
        selectedRegion === 'All Regions' ||
        (log.region && log.region.toLowerCase().includes(selectedRegion.toLowerCase())) ||
        log.region === 'All Regions';

      const q = searchQuery.toLowerCase().trim();
      const matchesSearch =
        !q ||
        log.action.toLowerCase().includes(q) ||
        log.details.toLowerCase().includes(q) ||
        (log.user_name && log.user_name.toLowerCase().includes(q)) ||
        (log.user_email && log.user_email.toLowerCase().includes(q)) ||
        (log.user_type && log.user_type.toLowerCase().includes(q)) ||
        (log.region && log.region.toLowerCase().includes(q));

      return matchesRegion && matchesSearch;
    });
  }, [activityLogs, selectedRegion, searchQuery]);

  // Handle Export Regional Alerts
  const handleExportAlerts = () => {
    const dataToExport = filteredAlerts.length > 0 ? filteredAlerts : alerts;
    exportRegionalAlertsToCSV(dataToExport);
    showNotice(`Successfully exported ${dataToExport.length} regional alerts to CSV.`);
  };

  // Handle Export User Activity Logs
  const handleExportLogs = () => {
    const dataToExport = filteredLogs.length > 0 ? filteredLogs : activityLogs;
    exportUserActivityLogsToCSV(dataToExport);
    showNotice(`Successfully exported ${dataToExport.length} user activity logs to CSV.`);
  };

  // Handle Export Both in One Action
  const handleExportAll = () => {
    exportRegionalAlertsToCSV(alerts, 'agro_all_regional_alerts');
    setTimeout(() => {
      exportUserActivityLogsToCSV(activityLogs, 'agro_all_user_activity_logs');
    }, 400);
    showNotice(`Successfully exported both Regional Alerts (${alerts.length}) and Activity Logs (${activityLogs.length}) as CSV files.`);
  };

  const showNotice = (msg: string) => {
    setExportNotice(msg);
    setTimeout(() => {
      setExportNotice(null);
    }, 4500);
  };

  const handleCopySql = () => {
    navigator.clipboard.writeText(BACKEND_SQL_QUERY);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2500);
  };

  return (
    <Card className="border border-gray-200 dark:border-gray-700 shadow-md">
      {/* Header and Quick Download CTAs */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 pb-4 border-b border-gray-200 dark:border-gray-700">
        <div>
          <div className="flex items-center gap-2">
            <span className="p-2 bg-green-100 text-green-700 rounded-lg">
              <DownloadIcon className="w-5 h-5 text-green-700" />
            </span>
            <h3 className="text-xl font-bold text-gray-900 dark:text-white">
              Audit Logs & CSV Export Center
            </h3>
          </div>
          <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
            Export regional alert notifications, commodity price shocks, and user system activity logs into CSV format for regulatory reporting and auditing.
          </p>
        </div>

        {/* Download Buttons Group */}
        <div className="flex flex-wrap items-center gap-2">
          <Button
            onClick={handleExportAlerts}
            className="inline-flex items-center gap-1.5 text-xs bg-amber-600 hover:bg-amber-700 text-white font-medium py-2 px-3 rounded-lg shadow-sm"
            title="Download regional alert history as CSV"
          >
            <DownloadIcon className="w-3.5 h-3.5" />
            <span>Export Alerts CSV ({filteredAlerts.length})</span>
          </Button>

          <Button
            onClick={handleExportLogs}
            className="inline-flex items-center gap-1.5 text-xs bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-3 rounded-lg shadow-sm"
            title="Download user activity logs as CSV"
          >
            <DownloadIcon className="w-3.5 h-3.5" />
            <span>Export Activity Logs CSV ({filteredLogs.length})</span>
          </Button>

          <Button
            onClick={handleExportAll}
            className="inline-flex items-center gap-1.5 text-xs bg-green-700 hover:bg-green-800 text-white font-semibold py-2 px-3.5 rounded-lg shadow-sm"
            title="Export all data tables"
          >
            <FileTextIcon className="w-3.5 h-3.5" />
            <span>Export All (Dual CSV)</span>
          </Button>

          <button
            onClick={loadData}
            disabled={isLoading}
            className="p-2 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
            title="Refresh latest live logs"
          >
            <RefreshCwIcon className={`w-4 h-4 ${isLoading ? 'animate-spin text-green-600' : ''}`} />
          </button>
        </div>
      </div>

      {/* Export Notice Banner */}
      {exportNotice && (
        <div className="mt-3 p-3 bg-green-50 border border-green-200 rounded-lg flex items-center justify-between text-xs text-green-800 animate-fade-in">
          <span className="flex items-center gap-2 font-medium">
            <CheckCircleIcon className="w-4 h-4 text-green-600" />
            {exportNotice}
          </span>
          <button onClick={() => setExportNotice(null)} className="text-green-600 hover:text-green-900 font-bold">
            ✕
          </button>
        </div>
      )}

      {/* Tabs Navigation */}
      <div className="flex border-b border-gray-200 dark:border-gray-700 mt-4">
        <button
          onClick={() => setActiveTab('alerts')}
          className={`py-2.5 px-4 font-medium text-xs border-b-2 flex items-center gap-1.5 transition-colors ${
            activeTab === 'alerts'
              ? 'border-green-600 text-green-700 dark:text-green-400 font-semibold'
              : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400'
          }`}
        >
          <AlertTriangleIcon className="w-4 h-4" />
          <span>Regional Alerts History</span>
          <span className="ml-1 bg-amber-100 text-amber-800 text-[10px] px-1.5 py-0.5 rounded-full font-bold">
            {alerts.length}
          </span>
        </button>

        <button
          onClick={() => setActiveTab('activity')}
          className={`py-2.5 px-4 font-medium text-xs border-b-2 flex items-center gap-1.5 transition-colors ${
            activeTab === 'activity'
              ? 'border-green-600 text-green-700 dark:text-green-400 font-semibold'
              : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400'
          }`}
        >
          <UsersIcon className="w-4 h-4" />
          <span>User Activity Logs</span>
          <span className="ml-1 bg-blue-100 text-blue-800 text-[10px] px-1.5 py-0.5 rounded-full font-bold">
            {activityLogs.length}
          </span>
        </button>

        <button
          onClick={() => setActiveTab('sql')}
          className={`py-2.5 px-4 font-medium text-xs border-b-2 flex items-center gap-1.5 transition-colors ${
            activeTab === 'sql'
              ? 'border-green-600 text-green-700 dark:text-green-400 font-semibold'
              : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400'
          }`}
        >
          <DatabaseIcon className="w-4 h-4" />
          <span>Supabase Backend SQL Code</span>
          <span className="ml-1 bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 text-[10px] px-1.5 py-0.5 rounded-full font-mono">
            .sql
          </span>
        </button>
      </div>

      {/* Filter and Search Bar (Active on 'alerts' and 'activity' tabs) */}
      {activeTab !== 'sql' && (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 my-4">
          {/* Search Box */}
          <div className="relative">
            <SearchIcon className="w-4 h-4 text-gray-400 absolute left-3 top-2.5" />
            <input
              type="text"
              placeholder={activeTab === 'alerts' ? "Search alerts by title or region..." : "Search user, action, email, region..."}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-3 py-1.5 text-xs bg-gray-50 dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-green-500"
            />
          </div>

          {/* Region Filter */}
          <div className="flex items-center gap-1.5">
            <FilterIcon className="w-3.5 h-3.5 text-gray-400" />
            <select
              value={selectedRegion}
              onChange={(e) => setSelectedRegion(e.target.value)}
              className="w-full py-1.5 px-2 text-xs bg-gray-50 dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-green-500"
            >
              {GHANA_REGIONS.map(reg => (
                <option key={reg} value={reg}>{reg}</option>
              ))}
            </select>
          </div>

          {/* Severity / Role Filter */}
          {activeTab === 'alerts' ? (
            <select
              value={selectedSeverity}
              onChange={(e) => setSelectedSeverity(e.target.value)}
              className="py-1.5 px-2 text-xs bg-gray-50 dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-green-500"
            >
              <option value="all">All Severities (Critical, Warning, Info)</option>
              <option value="critical">Critical Only</option>
              <option value="warning">Warning Only</option>
              <option value="info">Info Only</option>
            </select>
          ) : (
            <div className="text-xs text-gray-500 flex items-center justify-end px-2">
              Showing {filteredLogs.length} of {activityLogs.length} logged events
            </div>
          )}
        </div>
      )}

      {/* Tab 1: Regional Alerts Table */}
      {activeTab === 'alerts' && (
        <div className="overflow-x-auto border border-gray-200 dark:border-gray-700 rounded-lg">
          <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700 text-left text-xs">
            <thead className="bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300 uppercase font-semibold">
              <tr>
                <th className="py-2.5 px-3">Type</th>
                <th className="py-2.5 px-3">Region</th>
                <th className="py-2.5 px-3">Severity</th>
                <th className="py-2.5 px-3">Title & Message</th>
                <th className="py-2.5 px-3">Recorded Time</th>
                <th className="py-2.5 px-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-gray-800 bg-white dark:bg-gray-900">
              {filteredAlerts.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-8 text-center text-gray-400">
                    No regional alerts found matching criteria.
                  </td>
                </tr>
              ) : (
                filteredAlerts.map((alert, idx) => (
                  <tr key={alert.id || idx} className="hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors">
                    <td className="py-2.5 px-3 whitespace-nowrap">
                      <span className={`inline-flex items-center gap-1 font-semibold px-2 py-0.5 rounded-full text-[10px] ${
                        alert.type === 'weather'
                          ? 'bg-yellow-100 text-yellow-800'
                          : alert.type === 'price'
                          ? 'bg-green-100 text-green-800'
                          : 'bg-blue-100 text-blue-800'
                      }`}>
                        {alert.type === 'weather' && <AlertTriangleIcon className="w-3 h-3 text-yellow-600" />}
                        {alert.type === 'price' && <TagIcon className="w-3 h-3 text-green-600" />}
                        {alert.type.toUpperCase()}
                      </span>
                    </td>
                    <td className="py-2.5 px-3 font-medium text-gray-800 dark:text-gray-200 whitespace-nowrap">
                      {alert.region}
                    </td>
                    <td className="py-2.5 px-3 whitespace-nowrap">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        alert.severity === 'critical'
                          ? 'bg-red-100 text-red-700'
                          : alert.severity === 'warning'
                          ? 'bg-amber-100 text-amber-700'
                          : 'bg-gray-100 text-gray-700'
                      }`}>
                        {alert.severity.toUpperCase()}
                      </span>
                    </td>
                    <td className="py-2.5 px-3">
                      <div className="font-semibold text-gray-900 dark:text-gray-100">{alert.title}</div>
                      <div className="text-gray-500 text-[11px] line-clamp-2 mt-0.5">{alert.message}</div>
                    </td>
                    <td className="py-2.5 px-3 text-gray-500 text-[11px] whitespace-nowrap">
                      {alert.created_at ? new Date(alert.created_at).toLocaleString() : 'N/A'}
                    </td>
                    <td className="py-2.5 px-3 text-right whitespace-nowrap">
                      <button
                        onClick={() => exportRegionalAlertsToCSV([alert], `alert_${alert.id || idx}`)}
                        className="text-xs text-green-700 hover:text-green-900 font-medium inline-flex items-center gap-1"
                        title="Export this single alert row to CSV"
                      >
                        <DownloadIcon className="w-3 h-3" />
                        <span>CSV</span>
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}

      {/* Tab 2: User Activity Logs Table */}
      {activeTab === 'activity' && (
        <div className="overflow-x-auto border border-gray-200 dark:border-gray-700 rounded-lg">
          <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700 text-left text-xs">
            <thead className="bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300 uppercase font-semibold">
              <tr>
                <th className="py-2.5 px-3">Timestamp</th>
                <th className="py-2.5 px-3">User & Role</th>
                <th className="py-2.5 px-3">Action</th>
                <th className="py-2.5 px-3">Region</th>
                <th className="py-2.5 px-3">Event Details</th>
                <th className="py-2.5 px-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-gray-800 bg-white dark:bg-gray-900">
              {filteredLogs.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-8 text-center text-gray-400">
                    No user activity logs found matching criteria.
                  </td>
                </tr>
              ) : (
                filteredLogs.map((log, idx) => (
                  <tr key={log.id || idx} className="hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors">
                    <td className="py-2.5 px-3 text-gray-500 text-[11px] whitespace-nowrap">
                      {new Date(log.created_at).toLocaleString()}
                    </td>
                    <td className="py-2.5 px-3 whitespace-nowrap">
                      <div className="font-semibold text-gray-800 dark:text-gray-200">
                        {log.user_name || 'Anonymous User'}
                      </div>
                      <div className="text-[10px] text-gray-400">
                        {log.user_email || 'No Email'} • <span className="uppercase text-blue-600 font-bold">{log.user_type || 'farmer'}</span>
                      </div>
                    </td>
                    <td className="py-2.5 px-3 whitespace-nowrap">
                      <span className="bg-gray-100 dark:bg-gray-800 text-gray-800 dark:text-gray-200 font-mono text-[10px] px-2 py-0.5 rounded border border-gray-200 dark:border-gray-700">
                        {log.action}
                      </span>
                    </td>
                    <td className="py-2.5 px-3 text-gray-700 dark:text-gray-300 whitespace-nowrap font-medium">
                      {log.region || 'All Regions'}
                    </td>
                    <td className="py-2.5 px-3">
                      <div className="text-gray-800 dark:text-gray-200">{log.details}</div>
                      {log.metadata && Object.keys(log.metadata).length > 0 && (
                        <div className="text-[10px] text-gray-400 font-mono mt-0.5 truncate max-w-xs">
                          {JSON.stringify(log.metadata)}
                        </div>
                      )}
                    </td>
                    <td className="py-2.5 px-3 text-right whitespace-nowrap">
                      <button
                        onClick={() => exportUserActivityLogsToCSV([log], `log_${log.id || idx}`)}
                        className="text-xs text-blue-700 hover:text-blue-900 font-medium inline-flex items-center gap-1"
                        title="Export this single log row to CSV"
                      >
                        <DownloadIcon className="w-3 h-3" />
                        <span>CSV</span>
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}

      {/* Tab 3: Supabase Backend SQL Code */}
      {activeTab === 'sql' && (
        <div className="space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-3 bg-indigo-50 dark:bg-indigo-950/40 border border-indigo-200 dark:border-indigo-800 rounded-lg">
            <div className="flex items-center gap-2">
              <DatabaseIcon className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
              <div>
                <h4 className="text-xs font-bold text-indigo-900 dark:text-indigo-200">
                  Supabase Backend SQL Deployment
                </h4>
                <p className="text-[11px] text-indigo-700 dark:text-indigo-300">
                  Paste this script into your Supabase Dashboard SQL Editor to instantiate the tables, RLS security rules, triggers, and CSV export views.
                </p>
              </div>
            </div>
            <Button
              onClick={handleCopySql}
              className={`inline-flex items-center gap-1.5 text-xs px-3.5 py-1.5 rounded-lg font-semibold shadow-sm transition-all whitespace-nowrap ${
                copiedSql
                  ? 'bg-green-600 text-white'
                  : 'bg-indigo-600 hover:bg-indigo-700 text-white'
              }`}
            >
              {copiedSql ? <CheckIcon className="w-4 h-4" /> : <CopyIcon className="w-4 h-4" />}
              <span>{copiedSql ? 'Copied to Clipboard!' : 'Copy SQL Script'}</span>
            </Button>
          </div>

          <div className="relative">
            <pre className="bg-gray-900 text-gray-100 p-4 rounded-lg font-mono text-[11px] leading-relaxed overflow-x-auto max-h-[380px] border border-gray-800">
              {BACKEND_SQL_QUERY}
            </pre>
          </div>

          <div className="p-3 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg text-xs text-gray-600 dark:text-gray-300 space-y-1">
            <p className="font-bold text-gray-800 dark:text-gray-100">Direct SQL Execution Instructions:</p>
            <ol className="list-decimal list-inside space-y-1 text-gray-500 dark:text-gray-400 text-[11px]">
              <li>Log in to your <strong>Supabase Dashboard</strong> and open your project.</li>
              <li>Navigate to the <strong>SQL Editor</strong> on the left-hand navigation bar.</li>
              <li>Click <strong>+ New Query</strong>, paste the copied SQL script, and click <strong>Run</strong>.</li>
              <li>Your database will immediately be ready to stream Realtime push alerts and log full audit histories!</li>
            </ol>
          </div>
        </div>
      )}
    </Card>
  );
};

export default AdminAuditExport;
