
import React, { useState, useRef } from 'react';
import { diagnosePlant } from '../services/geminiService';
import { fileToBase64 } from '../utils';
import { uploadUserFile } from '../services/storageService';
import Card from './common/Card';
import Button from './common/Button';
import { marked } from 'marked';
import { useNotifications } from '../contexts/NotificationContext';
import type { User } from '../types';

interface PestDiagnosisProps {
  user?: User | null;
}

const PestDiagnosis: React.FC<PestDiagnosisProps> = ({ user }) => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [diagnosisResult, setDiagnosisResult] = useState<string>('');
  const [error, setError] = useState<string>('');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { addNotification } = useNotifications();

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (file.size > 4 * 1024 * 1024) { 
        setError('File is too large. Please select an image under 4MB.');
        return;
      }
      setSelectedFile(file);
      setPreviewUrl(URL.createObjectURL(file));
      setDiagnosisResult('');
      setError('');
    }
  };

  const handleDiagnose = async () => {
    if (!selectedFile) {
      setError('Please select an image first.');
      return;
    }

    setIsLoading(true);
    setError('');
    setDiagnosisResult('');

    try {
      // 1. Get Diagnosis
      const base64Image = await fileToBase64(selectedFile);
      const result = await diagnosePlant(base64Image, selectedFile.type);
      setDiagnosisResult(result);

      // 2. If user is logged in, upload image and save result to history
      if (user && user.uid) {
        try {
           await uploadUserFile(
             user.uid,
             selectedFile,
             'pest-diagnosis',
             result, // The diagnosis text is the AI summary
             'Plant diagnosis generated by AI'
           );
           addNotification({ type: 'pest', title: 'Saved to History', message: 'Diagnosis and image saved to your profile.', view: 'PROFILE' });
        } catch (uploadError) {
          console.error("Failed to save to history:", uploadError);
          // Don't block the user from seeing the result if save fails
          addNotification({ type: 'pest', title: 'Save Failed', message: 'Could not save diagnosis to history.', view: 'DIAGNOSIS' });
        }
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'An unknown error occurred.';
      setError(`Failed to process image: ${errorMessage}`);
    } finally {
      setIsLoading(false);
    }
  };
  
  const triggerFileSelect = () => fileInputRef.current?.click();
  
  const getSanitizedHtml = (markdown: string) => {
    const rawMarkup = marked.parse(markdown);
    return { __html: rawMarkup };
  };

  return (
    <Card>
      <h2 className="text-xl font-bold mb-4 text-green-700">Pest & Disease Diagnosis</h2>
      <p className="text-gray-600 mb-4">Upload a photo of a diseased leaf to get a preliminary diagnosis and treatment advice.</p>
      
      {!user && (
         <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-4">
            <p className="text-sm text-yellow-700">
                Log in to automatically save your diagnoses and images to your history.
            </p>
         </div>
      )}

      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileChange}
        accept="image/png, image/jpeg"
        className="hidden"
        aria-label="Upload plant image"
      />
      
      <div className="flex flex-col sm:flex-row items-center gap-4">
        <button 
          type="button"
          onClick={triggerFileSelect}
          className="w-full sm:w-48 h-48 border-2 border-dashed border-gray-300 rounded-lg flex items-center justify-center text-center text-gray-500 cursor-pointer hover:border-green-400 hover:bg-green-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
        >
          {previewUrl ? (
            <img src={previewUrl} alt="Selected leaf" className="w-full h-full object-cover rounded-lg" />
          ) : (
            <span>Click to select image</span>
          )}
        </button>
        
        <div className="flex-grow">
          <Button onClick={handleDiagnose} isLoading={isLoading} disabled={!selectedFile || isLoading}>
            {isLoading ? 'Analyzing...' : 'Diagnose Plant'}
          </Button>
          {selectedFile && <p className="text-sm text-gray-500 mt-2">Selected: {selectedFile.name}</p>}
        </div>
      </div>

      {error && <div className="mt-4 text-red-600 bg-red-100 p-3 rounded-md" role="alert">{error}</div>}

      {isLoading && <div className="mt-4 text-center text-gray-600">Analyzing image, please wait...</div>}

      {diagnosisResult && (
        <div className="mt-6">
          <h3 className="text-lg font-semibold mb-2 text-gray-800">Diagnosis Result</h3>
          <div 
            className="prose prose-sm max-w-none bg-gray-50 p-4 rounded-lg border text-gray-900 [&>h3]:text-gray-900 [&>h3]:font-bold [&>ul]:list-disc [&>ul]:pl-5 [&>strong]:text-gray-900"
            dangerouslySetInnerHTML={getSanitizedHtml(diagnosisResult)}
           />
        </div>
      )}
    </Card>
  );
};

export default PestDiagnosis;
