import React, { useState } from 'react';
import { useNotifications } from '../contexts/NotificationContext';
import { GhanaRegion, View } from '../types';
import { 
  XIcon, 
  BellIcon, 
  BellRingIcon, 
  CloudIcon, 
  TagIcon, 
  CheckIcon, 
  CopyIcon, 
  AlertTriangleIcon, 
  ExternalLinkIcon 
} from './common/icons';

const GHANA_REGIONS: GhanaRegion[] = [
  'Greater Accra',
  'Ashanti',
  'Bono / Techiman',
  'Northern / Tamale',
  'Eastern',
  'Western',
  'Central',
  'Volta',
  'Upper East',
  'Upper West',
  'All Regions'
];

const SUPABASE_BACKEND_SQL = `-- ====================================================================
-- SUPABASE MIGRATION: REGIONAL PUSH NOTIFICATIONS & COMMODITY ALERTS
-- Ghana Farmers Market℠
-- Run in Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql
-- ====================================================================

-- 1. REGIONAL ALERTS TABLE
CREATE TABLE IF NOT EXISTS public.regional_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('weather', 'price', 'general')),
    region TEXT NOT NULL DEFAULT 'All Regions',
    severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'critical')) DEFAULT 'warning',
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_regional_alerts_region_created 
ON public.regional_alerts (region, created_at DESC);

-- 2. USER NOTIFICATION PREFERENCES TABLE
CREATE TABLE IF NOT EXISTS public.user_notification_preferences (
    user_id TEXT PRIMARY KEY,
    region TEXT NOT NULL DEFAULT 'All Regions',
    push_enabled BOOLEAN NOT NULL DEFAULT true,
    weather_alerts_enabled BOOLEAN NOT NULL DEFAULT true,
    price_alerts_enabled BOOLEAN NOT NULL DEFAULT true,
    price_threshold_pct NUMERIC(5, 2) NOT NULL DEFAULT 15.00,
    sound_enabled BOOLEAN NOT NULL DEFAULT true,
    web_push_subscription JSONB DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.regional_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notification_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to regional alerts"
ON public.regional_alerts FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow authenticated users to insert regional alerts"
ON public.regional_alerts FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow public read/write to own preferences"
ON public.user_notification_preferences FOR ALL TO anon, authenticated
USING (true) WITH CHECK (true);

-- 4. REALTIME BROADCAST ENABLING
-- Allows client apps to receive instantaneous push alerts via Supabase Realtime
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'regional_alerts'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.regional_alerts;
    END IF;
END $$;

-- 5. AUTOMATED PRICE SURGE TRIGGER PROCEDURE
CREATE TABLE IF NOT EXISTS public.commodity_price_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop TEXT NOT NULL,
    market TEXT NOT NULL,
    region TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    previous_price NUMERIC(10, 2),
    unit TEXT NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE OR REPLACE FUNCTION public.fn_check_price_surge()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    pct_change NUMERIC(6, 2);
BEGIN
    IF NEW.previous_price IS NOT NULL AND NEW.previous_price > 0 THEN
        pct_change := ROUND(((NEW.price - NEW.previous_price) / NEW.previous_price) * 100, 2);
        
        IF pct_change >= 15.00 THEN
            INSERT INTO public.regional_alerts (
                type, region, severity, title, message, metadata
            ) VALUES (
                'price',
                NEW.region,
                'warning',
                'Market Price Surge: ' || NEW.crop || ' (+' || pct_change || '%)',
                NEW.crop || ' wholesale price surged to GHS ' || NEW.price || ' per ' || NEW.unit || ' at ' || NEW.market || '.',
                jsonb_build_object('crop', NEW.crop, 'market', NEW.market, 'price', NEW.price, 'pct_change', pct_change)
            );
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_commodity_price_surge ON public.commodity_price_logs;
CREATE TRIGGER trg_commodity_price_surge
AFTER INSERT ON public.commodity_price_logs
FOR EACH ROW EXECUTE FUNCTION public.fn_check_price_surge();

-- 6. SAMPLE INITIAL BROADCASTS
INSERT INTO public.regional_alerts (type, region, severity, title, message)
VALUES 
    ('weather', 'Southern Coastal', 'critical', 'Heavy Squall & Thunderstorm Alert', 'Severe convective front approaching Greater Accra farmlands.'),
    ('price', 'Bono / Techiman', 'warning', 'Maize Wholesale Surge (+18%)', 'Techiman Market 100kg white maize bags jumped to GHS 260.');`;

interface RegionalPushSettingsModalProps {
  setActiveView: (view: View) => void;
}

export const RegionalPushSettingsModal: React.FC<RegionalPushSettingsModalProps> = ({ setActiveView }) => {
  const {
    isSettingsOpen,
    setIsSettingsOpen,
    pushPermission,
    isPushSupported,
    requestPushPermission,
    userRegion,
    setUserRegion,
    preferences,
    updatePreferences,
    sendRegionalPushNotification,
    alertHistory,
    clearAlertHistory
  } = useNotifications();

  const [activeTab, setActiveTab] = useState<'settings' | 'history' | 'sql'>('settings');
  const [copiedSql, setCopiedSql] = useState(false);
  const [testSent, setTestSent] = useState<string | null>(null);

  if (!isSettingsOpen) return null;

  const handleCopySql = async () => {
    try {
      await navigator.clipboard.writeText(SUPABASE_BACKEND_SQL);
      setCopiedSql(true);
      setTimeout(() => setCopiedSql(false), 2500);
    } catch {
      // Fallback
    }
  };

  const handleSimulateWeatherAlert = () => {
    sendRegionalPushNotification({
      type: 'weather',
      title: 'Severe Weather Warning',
      message: `Torrential rainfall and high convective squalls (45 km/h) heading across ${userRegion}. Secure storage sheds and protect dried crops.`,
      region: userRegion,
      severity: 'critical',
      view: 'WEATHER',
      forceBrowserPush: true
    });
    setTestSent('Weather Alert Sent!');
    setTimeout(() => setTestSent(null), 3000);
  };

  const handleSimulatePriceAlert = () => {
    sendRegionalPushNotification({
      type: 'price',
      title: `Price Surge Alert (${userRegion})`,
      message: `Maize wholesale prices surged +18% to GHS 275 per 100kg bag in local regional trading centers. Market trend is Upward.`,
      region: userRegion,
      severity: 'warning',
      view: 'PRICES',
      forceBrowserPush: true
    });
    setTestSent('Price Surge Alert Sent!');
    setTimeout(() => setTestSent(null), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/70 backdrop-blur-sm animate-fade-in">
      <div 
        className="bg-gray-800 text-gray-100 rounded-2xl max-w-2xl w-full max-h-[90vh] flex flex-col shadow-2xl border border-gray-700 overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-700 bg-gray-900/70">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-green-500/20 text-green-400 rounded-xl border border-green-500/30">
              <BellRingIcon className="w-6 h-6 text-green-400 animate-pulse" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white flex items-center gap-2">
                Regional Push Notifications
                <span className="text-[10px] bg-green-900/60 text-green-300 font-bold px-2 py-0.5 rounded-full border border-green-600/40">
                  LIVE
                </span>
              </h3>
              <p className="text-xs text-gray-400">Extreme weather & market price fluctuation alerts</p>
            </div>
          </div>
          <button
            onClick={() => setIsSettingsOpen(false)}
            className="p-1.5 text-gray-400 hover:text-white rounded-lg hover:bg-gray-700/60 transition-colors"
          >
            <XIcon className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="flex border-b border-gray-700 bg-gray-900/40 text-xs font-semibold px-4">
          <button
            onClick={() => setActiveTab('settings')}
            className={`py-3 px-4 border-b-2 font-medium transition-all ${
              activeTab === 'settings'
                ? 'border-green-500 text-green-400 bg-gray-800/60'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            Alert Preferences
          </button>
          <button
            onClick={() => setActiveTab('history')}
            className={`py-3 px-4 border-b-2 font-medium transition-all flex items-center gap-1.5 ${
              activeTab === 'history'
                ? 'border-green-500 text-green-400 bg-gray-800/60'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            <span>Alert History</span>
            {alertHistory.length > 0 && (
              <span className="px-1.5 py-0.2 bg-green-700 text-white rounded-full text-[10px]">
                {alertHistory.length}
              </span>
            )}
          </button>
          <button
            onClick={() => setActiveTab('sql')}
            className={`py-3 px-4 border-b-2 font-medium transition-all flex items-center gap-1.5 ${
              activeTab === 'sql'
                ? 'border-green-500 text-green-400 bg-gray-800/60'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            <span>Supabase Backend SQL</span>
            <span className="px-1.5 py-0.2 bg-indigo-900/80 text-indigo-300 rounded text-[9px] border border-indigo-700/50">
              PostgreSQL
            </span>
          </button>
        </div>

        {/* Body Content */}
        <div className="p-5 overflow-y-auto space-y-5 text-sm flex-1">
          {/* TAB 1: SETTINGS */}
          {activeTab === 'settings' && (
            <div className="space-y-5">
              {/* Push Permission Banner */}
              <div className="bg-gray-900/80 border border-gray-700 p-4 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="flex items-center gap-3">
                  <div className={`p-2 rounded-lg ${
                    pushPermission === 'granted' 
                      ? 'bg-emerald-500/20 text-emerald-400' 
                      : pushPermission === 'denied' 
                      ? 'bg-rose-500/20 text-rose-400' 
                      : 'bg-amber-500/20 text-amber-400'
                  }`}>
                    <BellIcon className="w-5 h-5" />
                  </div>
                  <div>
                    <div className="font-semibold text-white flex items-center gap-2">
                      Device Push Notifications
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                        pushPermission === 'granted'
                          ? 'bg-emerald-900/60 text-emerald-300 border border-emerald-600/50'
                          : pushPermission === 'denied'
                          ? 'bg-rose-900/60 text-rose-300 border border-rose-600/50'
                          : 'bg-amber-900/60 text-amber-300 border border-amber-600/50'
                      }`}>
                        {pushPermission === 'granted' ? 'Active' : pushPermission === 'denied' ? 'Blocked in Browser' : 'Not Granted'}
                      </span>
                    </div>
                    <p className="text-xs text-gray-400">
                      Receive alerts directly on your phone or PC screen even when working outside the browser tab.
                    </p>
                  </div>
                </div>

                {pushPermission !== 'granted' && (
                  <button
                    onClick={requestPushPermission}
                    className="sm:self-center px-3.5 py-2 bg-green-600 hover:bg-green-500 text-white font-semibold text-xs rounded-lg shadow-md transition-all whitespace-nowrap"
                  >
                    Enable Browser Push
                  </button>
                )}
              </div>

              {/* Target Region Selection */}
              <div className="bg-gray-900/50 border border-gray-700/80 p-4 rounded-xl space-y-2">
                <label className="block text-xs font-bold text-gray-300 uppercase tracking-wider">
                  Target Ghanaian Agricultural Region
                </label>
                <p className="text-xs text-gray-400">
                  Select your farming locality or market hub to receive filtered meteorological and commodity alerts.
                </p>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 pt-1">
                  {GHANA_REGIONS.map((region) => (
                    <button
                      key={region}
                      onClick={() => setUserRegion(region)}
                      className={`px-3 py-2 text-xs font-medium rounded-lg text-left border transition-all ${
                        userRegion === region
                          ? 'bg-green-600 text-white border-green-500 shadow-sm font-semibold'
                          : 'bg-gray-800 text-gray-300 border-gray-700 hover:border-gray-600 hover:bg-gray-750'
                      }`}
                    >
                      {region}
                    </button>
                  ))}
                </div>
              </div>

              {/* Toggles */}
              <div className="bg-gray-900/50 border border-gray-700/80 p-4 rounded-xl space-y-4">
                <h4 className="text-xs font-bold text-gray-300 uppercase tracking-wider">
                  Alert Subscriptions
                </h4>

                {/* Weather Toggle */}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <CloudIcon className="w-5 h-5 text-blue-400" />
                    <div>
                      <div className="font-semibold text-white">Extreme Weather Alerts</div>
                      <div className="text-xs text-gray-400">
                        Immediate squalls, storms, flash floods, and prolonged heat advisories for {userRegion}.
                      </div>
                    </div>
                  </div>
                  <input
                    type="checkbox"
                    checked={preferences.weather_alerts_enabled}
                    onChange={(e) => updatePreferences({ weather_alerts_enabled: e.target.checked })}
                    className="w-5 h-5 accent-green-600 rounded cursor-pointer"
                  />
                </div>

                {/* Price Fluctuations Toggle */}
                <div className="flex items-center justify-between border-t border-gray-800 pt-3">
                  <div className="flex items-center gap-3">
                    <TagIcon className="w-5 h-5 text-emerald-400" />
                    <div>
                      <div className="font-semibold text-white">Significant Market Price Fluctuations</div>
                      <div className="text-xs text-gray-400">
                        Instant notification when wholesale commodity prices in {userRegion} surge or plummet.
                      </div>
                    </div>
                  </div>
                  <input
                    type="checkbox"
                    checked={preferences.price_alerts_enabled}
                    onChange={(e) => updatePreferences({ price_alerts_enabled: e.target.checked })}
                    className="w-5 h-5 accent-green-600 rounded cursor-pointer"
                  />
                </div>

                {/* Price Threshold Slider */}
                {preferences.price_alerts_enabled && (
                  <div className="pl-8 pt-1 border-t border-gray-800/80">
                    <div className="flex justify-between text-xs text-gray-300 font-medium mb-1">
                      <span>Price Surge Sensitivity:</span>
                      <span className="text-green-400 font-bold">±{preferences.price_threshold_pct}% or greater</span>
                    </div>
                    <input
                      type="range"
                      min={5}
                      max={40}
                      step={5}
                      value={preferences.price_threshold_pct}
                      onChange={(e) => updatePreferences({ price_threshold_pct: Number(e.target.value) })}
                      className="w-full accent-green-500 cursor-pointer"
                    />
                    <div className="flex justify-between text-[10px] text-gray-500 mt-0.5">
                      <span>5% (High sensitivity)</span>
                      <span>15% (Recommended)</span>
                      <span>40% (Major shocks only)</span>
                    </div>
                  </div>
                )}

                {/* Sound Toggle */}
                <div className="flex items-center justify-between border-t border-gray-800 pt-3">
                  <div className="flex items-center gap-3">
                    <BellIcon className="w-5 h-5 text-amber-400" />
                    <div>
                      <div className="font-semibold text-white">Audio Alert Chime</div>
                      <div className="text-xs text-gray-400">
                        Plays a distinct melodic notification tone when an urgent alert arrives.
                      </div>
                    </div>
                  </div>
                  <input
                    type="checkbox"
                    checked={preferences.sound_enabled}
                    onChange={(e) => updatePreferences({ sound_enabled: e.target.checked })}
                    className="w-5 h-5 accent-green-600 rounded cursor-pointer"
                  />
                </div>
              </div>

              {/* Simulation Testing */}
              <div className="bg-gray-900/40 border border-gray-700/60 p-4 rounded-xl space-y-2">
                <div className="flex justify-between items-center">
                  <span className="text-xs font-bold text-gray-300 uppercase tracking-wider">
                    Simulate & Test Push Notifications
                  </span>
                  {testSent && (
                    <span className="text-xs text-emerald-400 font-semibold animate-pulse">
                      ✓ {testSent}
                    </span>
                  )}
                </div>
                <p className="text-xs text-gray-400">
                  Trigger a live notification right now to verify in-app alerts and browser push delivery.
                </p>
                <div className="flex flex-wrap gap-2 pt-1">
                  <button
                    onClick={handleSimulateWeatherAlert}
                    className="px-3 py-1.5 bg-blue-600/80 hover:bg-blue-600 text-white rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors shadow-sm"
                  >
                    <CloudIcon className="w-4 h-4" />
                    <span>Test Extreme Weather Alert</span>
                  </button>
                  <button
                    onClick={handleSimulatePriceAlert}
                    className="px-3 py-1.5 bg-emerald-600/80 hover:bg-emerald-600 text-white rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors shadow-sm"
                  >
                    <TagIcon className="w-4 h-4" />
                    <span>Test Market Price Surge</span>
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: HISTORY */}
          {activeTab === 'history' && (
            <div className="space-y-3">
              <div className="flex justify-between items-center pb-2 border-b border-gray-700">
                <span className="text-xs text-gray-400">
                  Recent push & in-app alerts dispatched for {userRegion}:
                </span>
                {alertHistory.length > 0 && (
                  <button
                    onClick={clearAlertHistory}
                    className="text-xs text-red-400 hover:text-red-300 font-semibold"
                  >
                    Clear History
                  </button>
                )}
              </div>

              {alertHistory.length === 0 ? (
                <div className="py-12 text-center text-gray-400 space-y-2">
                  <BellIcon className="w-10 h-10 mx-auto text-gray-600" />
                  <p className="font-semibold">No alerts recorded yet</p>
                  <p className="text-xs text-gray-500">
                    You will see extreme weather warnings and commodity price alerts recorded here as they occur.
                  </p>
                </div>
              ) : (
                <div className="space-y-2">
                  {alertHistory.map((item) => (
                    <div
                      key={item.id}
                      onClick={() => {
                        if (item.view) {
                          setActiveView(item.view);
                          setIsSettingsOpen(false);
                        }
                      }}
                      className={`p-3 rounded-xl border transition-all ${
                        item.severity === 'critical'
                          ? 'bg-red-950/30 border-red-800/60 hover:border-red-600'
                          : item.type === 'weather'
                          ? 'bg-blue-950/30 border-blue-800/60 hover:border-blue-600'
                          : 'bg-emerald-950/30 border-emerald-800/60 hover:border-emerald-600'
                      } ${item.view ? 'cursor-pointer' : ''}`}
                    >
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex items-center gap-2">
                          {item.type === 'weather' ? (
                            <CloudIcon className="w-4 h-4 text-blue-400 flex-shrink-0" />
                          ) : (
                            <TagIcon className="w-4 h-4 text-emerald-400 flex-shrink-0" />
                          )}
                          <span className="font-semibold text-white text-xs">{item.title}</span>
                          {item.region && (
                            <span className="text-[10px] bg-gray-800 text-gray-300 px-1.5 py-0.5 rounded border border-gray-700">
                              {item.region}
                            </span>
                          )}
                        </div>
                        <span className="text-[10px] text-gray-400 whitespace-nowrap">
                          {item.timestamp ? new Date(item.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'Recent'}
                        </span>
                      </div>
                      <p className="text-xs text-gray-300 mt-1 pl-6">{item.message}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* TAB 3: SUPABASE SQL */}
          {activeTab === 'sql' && (
            <div className="space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 bg-indigo-950/40 border border-indigo-800/60 p-3 rounded-xl">
                <div>
                  <h4 className="text-xs font-bold text-indigo-300 uppercase tracking-wider">
                    Supabase PostgreSQL Backend Migration
                  </h4>
                  <p className="text-xs text-gray-300">
                    Provides tables, RLS security policies, realtime broadcast channels, and automated price surge triggers.
                  </p>
                </div>
                <button
                  onClick={handleCopySql}
                  className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all shadow-md whitespace-nowrap"
                >
                  {copiedSql ? (
                    <>
                      <CheckIcon className="w-4 h-4 text-white" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <CopyIcon className="w-4 h-4" />
                      <span>Copy SQL Query</span>
                    </>
                  )}
                </button>
              </div>

              {/* Instructions */}
              <div className="bg-gray-900/60 border border-gray-700/80 p-3 rounded-xl text-xs space-y-1.5 text-gray-300">
                <div className="font-semibold text-white">How to execute on your Supabase Backend:</div>
                <ol className="list-decimal list-inside space-y-1 text-gray-400">
                  <li>Open your project dashboard on Supabase: <code className="bg-gray-800 px-1 py-0.5 rounded text-gray-200">https://supabase.com/dashboard/project/_/sql</code></li>
                  <li>Click <strong>New Query</strong>, paste the SQL below, and click <strong>Run</strong>.</li>
                  <li>The app will automatically sync real-time alerts across all regional users and trigger push notifications on price shocks!</li>
                </ol>
              </div>

              {/* Code Viewer */}
              <div className="relative rounded-xl overflow-hidden border border-gray-700 bg-gray-950 font-mono text-xs">
                <div className="flex items-center justify-between px-3 py-1.5 bg-gray-900 border-b border-gray-800 text-[11px] text-gray-400">
                  <span>supabase/migrations/20260928_regional_push_notifications.sql</span>
                  <button
                    onClick={handleCopySql}
                    className="hover:text-white transition-colors flex items-center gap-1"
                  >
                    {copiedSql ? 'Copied' : 'Copy'}
                  </button>
                </div>
                <pre className="p-3 text-gray-300 overflow-x-auto max-h-72 text-[11px] leading-relaxed select-all">
                  {SUPABASE_BACKEND_SQL}
                </pre>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-5 py-3 border-t border-gray-700 bg-gray-900/60 text-xs">
          <div className="text-gray-400">
            Active Region: <strong className="text-white">{userRegion}</strong>
          </div>
          <button
            onClick={() => setIsSettingsOpen(false)}
            className="px-4 py-1.5 bg-gray-700 hover:bg-gray-600 text-white font-medium rounded-lg transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
