-- ====================================================================
-- SUPABASE MIGRATION: ADMIN AUDIT LOGS & CSV EXPORT BACKEND
-- Ghana Farmers Market℠
-- ====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. USER ACTIVITY LOGS TABLE
-- Tracks farmer, buyer, seller, and administrator actions for compliance and monitoring
CREATE TABLE IF NOT EXISTS public.user_activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    user_name TEXT,
    user_email TEXT,
    user_type TEXT DEFAULT 'farmer' CHECK (user_type IN ('farmer', 'buyer', 'seller', 'admin', 'system')),
    action TEXT NOT NULL,
    details TEXT NOT NULL,
    region TEXT NOT NULL DEFAULT 'All Regions',
    ip_address TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optimize queries for admin dashboard filtering and CSV exports
CREATE INDEX IF NOT EXISTS idx_user_activity_logs_created_at 
ON public.user_activity_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_activity_logs_action 
ON public.user_activity_logs (action);

CREATE INDEX IF NOT EXISTS idx_user_activity_logs_region 
ON public.user_activity_logs (region);

CREATE INDEX IF NOT EXISTS idx_user_activity_logs_user_id 
ON public.user_activity_logs (user_id);

-- 3. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.user_activity_logs ENABLE ROW LEVEL SECURITY;

-- Allow public and authenticated users to log actions
CREATE POLICY "Allow public insert to user_activity_logs"
ON public.user_activity_logs FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Allow admins or authenticated users to read activity logs
CREATE POLICY "Allow read access to user_activity_logs"
ON public.user_activity_logs FOR SELECT
TO anon, authenticated
USING (true);

-- 4. STORED PROCEDURE: RECORD USER ACTIVITY
CREATE OR REPLACE FUNCTION public.log_user_activity(
    p_user_id TEXT,
    p_user_name TEXT,
    p_user_email TEXT,
    p_user_type TEXT,
    p_action TEXT,
    p_details TEXT,
    p_region TEXT DEFAULT 'All Regions',
    p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_log_id BIGINT;
BEGIN
    INSERT INTO public.user_activity_logs (
        user_id,
        user_name,
        user_email,
        user_type,
        action,
        details,
        region,
        metadata,
        created_at
    )
    VALUES (
        p_user_id,
        p_user_name,
        p_user_email,
        COALESCE(p_user_type, 'farmer'),
        p_action,
        p_details,
        COALESCE(p_region, 'All Regions'),
        COALESCE(p_metadata, '{}'::jsonb),
        timezone('utc'::text, now())
    )
    RETURNING id INTO new_log_id;

    RETURN new_log_id;
END;
$$;

-- 5. FLATTENED CSV EXPORT VIEWS
-- Formats data directly for CSV streaming or SQL export tools

CREATE OR REPLACE VIEW public.v_export_regional_alerts AS
SELECT 
    id AS "Alert ID",
    type AS "Alert Type",
    region AS "Region",
    severity AS "Severity Level",
    title AS "Title",
    message AS "Message Content",
    COALESCE(metadata::text, '') AS "Metadata JSON",
    to_char(created_at, 'YYYY-MM-DD HH24:MI:SS') AS "Created At (UTC)",
    COALESCE(created_by::text, 'System') AS "Created By"
FROM public.regional_alerts
ORDER BY created_at DESC;

CREATE OR REPLACE VIEW public.v_export_user_activity_logs AS
SELECT 
    id AS "Log ID",
    to_char(created_at, 'YYYY-MM-DD HH24:MI:SS') AS "Timestamp (UTC)",
    COALESCE(user_id, 'Guest') AS "User ID",
    COALESCE(user_name, 'Anonymous') AS "User Name",
    COALESCE(user_email, 'N/A') AS "Email Address",
    COALESCE(user_type, 'farmer') AS "User Role",
    action AS "Action Taken",
    region AS "Region",
    details AS "Event Details",
    COALESCE(metadata::text, '') AS "Metadata JSON"
FROM public.user_activity_logs
ORDER BY created_at DESC;

-- 6. AUDIT SUMMARY METRICS FUNCTION
CREATE OR REPLACE FUNCTION public.get_audit_summary()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    total_alerts BIGINT;
    total_logs BIGINT;
    weather_alerts BIGINT;
    price_alerts BIGINT;
    unique_users BIGINT;
BEGIN
    SELECT count(*) INTO total_alerts FROM public.regional_alerts;
    SELECT count(*) INTO total_logs FROM public.user_activity_logs;
    SELECT count(*) INTO weather_alerts FROM public.regional_alerts WHERE type = 'weather';
    SELECT count(*) INTO price_alerts FROM public.regional_alerts WHERE type = 'price';
    SELECT count(DISTINCT user_id) INTO unique_users FROM public.user_activity_logs WHERE user_id IS NOT NULL;

    RETURN jsonb_build_object(
        'total_regional_alerts', total_alerts,
        'total_user_activity_logs', total_logs,
        'weather_alerts_count', weather_alerts,
        'price_alerts_count', price_alerts,
        'unique_active_users', unique_users,
        'generated_at', timezone('utc'::text, now())
    );
END;
$$;

-- 7. REALTIME PUBLICATION FOR LIVE AUDITING
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'user_activity_logs'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.user_activity_logs;
    END IF;
END $$;

-- 8. INITIAL SEED LOGS FOR GHANAIAN AGRICULTURAL ACTIVITY
INSERT INTO public.user_activity_logs (user_id, user_name, user_email, user_type, action, details, region, metadata, created_at)
VALUES
    (
        'usr-gh-001',
        'Kofi Mensah',
        'kofi.mensah@farmer.gh',
        'farmer',
        'PRICE_CHECK',
        'Queried wholesale price for White Maize at Techiman Market',
        'Bono / Techiman',
        '{"crop": "Maize", "market": "Techiman", "price": 260}'::jsonb,
        timezone('utc'::text, now()) - interval '15 minutes'
    ),
    (
        'usr-gh-002',
        'Akua Afriyie',
        'akua.afriyie@agrobuyer.gh',
        'buyer',
        'ORDER_PLACED',
        'Initiated purchase of 50 bags of Yam (Pona) from Ejura Farms',
        'Ashanti',
        '{"commodity": "Yam", "bags": 50, "total_ghs": 18500}'::jsonb,
        timezone('utc'::text, now()) - interval '45 minutes'
    ),
    (
        'usr-gh-003',
        'Ibrahim Alhassan',
        'i.alhassan@tamale-grain.com',
        'seller',
        'MARKET_LISTING_CREATED',
        'Listed 200 bags of Northern Yellow Soyabean at GHS 320/bag',
        'Northern / Tamale',
        '{"commodity": "Soyabean", "quantity": 200, "unitPrice": 320}'::jsonb,
        timezone('utc'::text, now()) - interval '90 minutes'
    ),
    (
        'usr-gh-004',
        'Kwame Osei',
        'k.osei@oseifarms.com',
        'farmer',
        'WEATHER_ALERT_TRIGGERED',
        'Received Severe Squall & Flash Flood Alert for Southern Coastal Belt',
        'Southern Coastal',
        '{"windSpeed": "38 km/h", "stormSeverity": "critical"}'::jsonb,
        timezone('utc'::text, now()) - interval '140 minutes'
    ),
    (
        'usr-gh-005',
        'Esi Dadzie',
        'esi.dadzie@centralproduce.gh',
        'farmer',
        'EQUIPMENT_RENTAL_INQUIRY',
        'Booked 50HP John Deere Tractor for plowing at Kasoa farming cluster',
        'Central',
        '{"equipment": "Tractor 50HP", "durationDays": 3, "costGhs": 1200}'::jsonb,
        timezone('utc'::text, now()) - interval '210 minutes'
    ),
    (
        'usr-admin-01',
        'App Administrator',
        'admin@agrosourcing.com',
        'admin',
        'ALERT_BROADCAST',
        'Broadcast nationwide storm caution for coastal marine and lake fishermen/farmers',
        'All Regions',
        '{"broadcastType": "extreme_weather", "severity": "warning"}'::jsonb,
        timezone('utc'::text, now()) - interval '300 minutes'
    )
ON CONFLICT DO NOTHING;
