-- ====================================================================
-- SUPABASE MIGRATION: REGIONAL PUSH NOTIFICATIONS & ALERTS
-- Ghana Farmers Market℠
-- Description: Sets up tables, Row Level Security, Realtime broadcast,
-- and automated trigger procedures for extreme weather alerts and
-- significant commodity price fluctuations by Ghanaian region.
-- ====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. REGIONAL ALERTS TABLE
-- Stores real-time broadcasts for extreme weather and market price shocks.
CREATE TABLE IF NOT EXISTS public.regional_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('weather', 'price', 'general')),
    region TEXT NOT NULL DEFAULT 'All Regions',
    severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'critical')) DEFAULT 'warning',
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Index for speedy regional filtering
CREATE INDEX IF NOT EXISTS idx_regional_alerts_region_created 
ON public.regional_alerts (region, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_regional_alerts_type 
ON public.regional_alerts (type);

-- 3. USER NOTIFICATION PREFERENCES TABLE
-- Tracks user-specific targeted regions, push notification permissions, and thresholds.
CREATE TABLE IF NOT EXISTS public.user_notification_preferences (
    user_id TEXT PRIMARY KEY, -- Supports auth.users uuid or local persistent ID
    region TEXT NOT NULL DEFAULT 'All Regions',
    push_enabled BOOLEAN NOT NULL DEFAULT true,
    weather_alerts_enabled BOOLEAN NOT NULL DEFAULT true,
    price_alerts_enabled BOOLEAN NOT NULL DEFAULT true,
    price_threshold_pct NUMERIC(5, 2) NOT NULL DEFAULT 15.00,
    sound_enabled BOOLEAN NOT NULL DEFAULT true,
    web_push_subscription JSONB DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.regional_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notification_preferences ENABLE ROW LEVEL SECURITY;

-- Regional Alerts Policies:
-- Anyone (anon and authenticated farmers/traders) can read alerts for their region
CREATE POLICY "Allow public read access to regional alerts"
ON public.regional_alerts FOR SELECT
TO anon, authenticated
USING (true);

-- Authenticated users, farmers or admins can insert/broadcast alerts
CREATE POLICY "Allow authenticated users to insert regional alerts"
ON public.regional_alerts FOR INSERT
TO authenticated
WITH CHECK (true);

-- User Notification Preferences Policies:
-- Users can read and manage their own preferences
CREATE POLICY "Allow public read/write to own preferences"
ON public.user_notification_preferences FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- 5. REALTIME BROADCAST ENABLING
-- Allows client apps to subscribe to live postgres changes via supabase.channel()
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'regional_alerts'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.regional_alerts;
    END IF;
END $$;

-- 6. STORED PROCEDURE: BROADCAST REGIONAL ALERT
-- Convenient SQL function to dispatch weather alerts or price surges
CREATE OR REPLACE FUNCTION public.broadcast_regional_alert(
    p_type TEXT,
    p_region TEXT,
    p_severity TEXT,
    p_title TEXT,
    p_message TEXT,
    p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_alert_id BIGINT;
BEGIN
    INSERT INTO public.regional_alerts (
        type,
        region,
        severity,
        title,
        message,
        metadata,
        created_at
    )
    VALUES (
        p_type,
        p_region,
        p_severity,
        p_title,
        p_message,
        p_metadata,
        timezone('utc'::text, now())
    )
    RETURNING id INTO new_alert_id;

    RETURN new_alert_id;
END;
$$;

-- 7. COMMODITY PRICE LOGS & AUTO-ALERT TRIGGER FUNCTION
-- Automatically creates a regional alert when a commodity price surges by >= threshold %
CREATE TABLE IF NOT EXISTS public.commodity_price_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop TEXT NOT NULL,
    market TEXT NOT NULL,
    region TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    previous_price NUMERIC(10, 2),
    unit TEXT NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE OR REPLACE FUNCTION public.fn_check_price_surge()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    pct_change NUMERIC(6, 2);
BEGIN
    IF NEW.previous_price IS NOT NULL AND NEW.previous_price > 0 THEN
        pct_change := ROUND(((NEW.price - NEW.previous_price) / NEW.previous_price) * 100, 2);
        
        -- If price jumped by 15% or more, trigger a push alert for that market's region
        IF pct_change >= 15.00 THEN
            INSERT INTO public.regional_alerts (
                type,
                region,
                severity,
                title,
                message,
                metadata
            )
            VALUES (
                'price',
                NEW.region,
                'warning',
                'Market Price Surge: ' || NEW.crop || ' (+' || pct_change || '%)',
                NEW.crop || ' wholesale price surged to GHS ' || NEW.price || ' per ' || NEW.unit || ' at ' || NEW.market || '.',
                jsonb_build_object(
                    'crop', NEW.crop,
                    'market', NEW.market,
                    'price', NEW.price,
                    'previous_price', NEW.previous_price,
                    'pct_change', pct_change
                )
            );
        -- If price crashed by 20% or more, alert buyers and aggregators
        ELSIF pct_change <= -20.00 THEN
             INSERT INTO public.regional_alerts (
                type,
                region,
                severity,
                title,
                message,
                metadata
            )
            VALUES (
                'price',
                NEW.region,
                'info',
                'Market Price Drop: ' || NEW.crop || ' (' || pct_change || '%)',
                NEW.crop || ' wholesale price dropped to GHS ' || NEW.price || ' per ' || NEW.unit || ' at ' || NEW.market || '. Good buying opportunity.',
                jsonb_build_object(
                    'crop', NEW.crop,
                    'market', NEW.market,
                    'price', NEW.price,
                    'previous_price', NEW.previous_price,
                    'pct_change', pct_change
                )
            );
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_commodity_price_surge ON public.commodity_price_logs;
CREATE TRIGGER trg_commodity_price_surge
AFTER INSERT ON public.commodity_price_logs
FOR EACH ROW
EXECUTE FUNCTION public.fn_check_price_surge();

-- 8. INITIAL SEED DATA FOR GHANAIAN REGIONS
INSERT INTO public.regional_alerts (type, region, severity, title, message, metadata)
VALUES 
    (
        'weather', 
        'Southern Coastal', 
        'critical', 
        'Heavy Thunderstorm & Squall Warning', 
        'Ghana Meteorological Agency (GMet) warns of heavy convective storm cells moving across Greater Accra and Central coastal farmlands with gusts exceeding 35 km/h.',
        '{"source": "GMet / MoFA", "expectedHours": 6}'::jsonb
    ),
    (
        'price', 
        'Bono / Techiman', 
        'warning', 
        'Maize Wholesale Price Surge (+18%)', 
        'Techiman Market recorded sharp demand increase: 100kg white maize bags climbed from GHS 220 to GHS 260 due to border transit inflows.',
        '{"crop": "Maize", "market": "Techiman Market", "price": 260, "unit": "100kg bag"}'::jsonb
    ),
    (
        'weather', 
        'Northern / Tamale', 
        'warning', 
        'Prolonged Dry Spell & Heat Advisory', 
        'Temperatures peaking at 36°C with relative humidity below 30%. Farmers are advised to apply mulch and protect seedlings.',
        '{"source": "Agro-Met Northern Sector", "temp": 36}'::jsonb
    )
ON CONFLICT DO NOTHING;
